# Generated by Django 5.2 on 2025-04-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_auto_20220302_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
