# Generated by Django 5.2 on 2025-04-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_alter_employees_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='contact',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
